a1=read.csv('countseed0.csv')
a2=read.csv('countseed1.csv')
a3=read.csv('countseed2.csv')
a4=read.csv('countseed3.csv')
a5=read.csv('countseed4.csv')
a6=read.csv('countseed5.csv')
a7=read.csv('countseed6.csv')
a8=read.csv('countseed7.csv')
a9=read.csv('countseed8.csv')
a10=read.csv('countseed9.csv')
p1=plot(a1$pixels,dnorm(a1$pixels,mean(a1$pixels),sd(a1$pixels)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
p2=plot(a2$pixels,dnorm(a2$pixels,mean(a2$pixels),sd(a2$pixels)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
p3=plot(a3$pixels,dnorm(a3$pixels,mean(a3$pixels),sd(a3$pixels)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
p4=plot(a4$pixels,dnorm(a4$pixels,mean(a4$pixels),sd(a4$pixels)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
p5=plot(a5$pixels,dnorm(a5$pixels,mean(a5$pixels),sd(a5$pixels)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
p6=plot(a6$pixels,dnorm(a6$pixels,mean(a6$pixels),sd(a6$pixels)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
p7=plot(a7$pixels,dnorm(a7$pixels,mean(a7$pixels),sd(a7$pixels)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
p8=plot(a8$pixels,dnorm(a8$pixels,mean(a8$pixels),sd(a8$pixels)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
p9=plot(a9$pixels,dnorm(a9$pixels,mean(a9$pixels),sd(a9$pixels)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
p10=plot(a10$pixels,dnorm(a10$pixels,mean(a10$pixels),sd(a10$pixels)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
a0=read.csv('countlist.csv')
p0=plot(a0$X73096,dnorm(a0$X73096,mean(a0$X73096),sd(a0$X73096)),main='seed pixel distribution',ylab = 'Frequency',xlab = 'Pixel count')
